### ISSUE TITLE
impossible to modify the currency.

### ISSUE THREAD

**Issue by franco27** [rajput-hemant/calculator#100] opened 2023-11-19 19:09 UTC
Hello,

I just tried the current version, 0.2.5.

When I'm in the currency conversion, I can't change a currency.
Whether it's the one at the top or the one at the bottom, when I click on it and go to the list, I select another currency and when I go back to the window it's still the same.

I've tried clicking on the flag or clicking on the circle or the box and nothing happens.

**Comment by gargamel17** [comment] 2023-11-19 19:34
Same problem here. In fact, the currency is well selected, but display is not refreshed. If you change tab and come back to currency screen you can see the currency previously selected

**Comment by rajput-hemant** [comment] 2023-11-19 19:43
Hello @franco27 & @gargamel17, 

Thank you for using my app and bringing up an issue. However, the app appears to be working fine in my testing on my device. I've attached a video demonstrating the same.

https://github.com/rajput-hemant/calculator/assets/68769346/6255872f-9d30-48e5-9c7d-b586ac2ba19a



If you're still experiencing the issue, I would greatly appreciate it if you could provide a screen recording for further investigation.

**Comment by franco27** [comment] 2023-11-19 20:00
I have just uninstalled and reinstalled the application.

By performing a long click on the new currency, I manage to display it in the window, but most of the time I have to click on it several times to make it appear in the currency conversion window.

And I am disappointed to see that the Colombian currency ( COP) is not on the list.

**Comment by gargamel17** [comment] 2023-11-19 20:13
Reinstalled the app and now it works as intended, thank you

**Comment by rajput-hemant** [comment] 2023-11-20 07:09
@franco27, @gargamel17 I'm glad to hear that the app is functioning well for you. If you come across any other issues, please feel free to let me know. Currently, the app relies on a free API service for exchange rates, which has limited currency support. I apologize for any inconvenience caused by the lack of support for the Colombian Peso (COP) in the app.

As for the reported issue, I'm closing it for now. If you have further concerns or encounter additional problems, don't hesitate to reach out.

**Closed** 2023-11-20 07:09 UTC
